FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml poetry.lock* requirements.txt ./
RUN pip install poetry && poetry config virtualenvs.create false && poetry install --no-root

COPY . /app/

CMD ["poetry", "run", "python", "manage.py", "process_round"]