"""
Django settings for weuro2025 project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS").split(",")

# Railway-specific settings
RAILWAY_STATIC_URL = config("RAILWAY_STATIC_URL", default="")
RAILWAY_ENVIRONMENT = config("RAILWAY_ENVIRONMENT", default="")

# Add Railway domains to allowed hosts
if RAILWAY_ENVIRONMENT:
    ALLOWED_HOSTS.extend(
        [f"*.up.railway.app", f"*.railway.app", "gsheir.com", "www.gsheir.com"]
    )

# Application definition
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "corsheaders",
]

LOCAL_APPS = [
    "game",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "weuro2025.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "weuro2025.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL", default="sqlite:///db.sqlite3"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Use WhiteNoise for static file serving
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom settings
LOGIN_URL = "/weuro2025_game/login/"
LOGIN_REDIRECT_URL = "/weuro2025_game/"
LOGOUT_REDIRECT_URL = "/"

# FBR API settings
FBR_API_BASE_URL = "https://fbrapi.com/"

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://gsheir.com",
]

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "game.services.fbr_api": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "game.management.commands": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Hardcoded football data
WEURO_2025_ROUNDS = [
    {
        "name": "Group Stage Week 1",
        "number": 1,
        "selection_opens": "2025-06-01T00:00:00Z",
        "selection_closes": "2025-07-02T15:00:00Z",
        "starts_at": "2025-07-02T16:00:00Z",
        "ends_at": "2025-07-06T15:59:59Z",
        "is_active": True,
        "is_completed": False,
    },
    {
        "name": "Group Stage Week 2",
        "number": 2,
        "selection_opens": "2025-07-02T16:00:00Z",
        "selection_closes": "2025-07-06T14:59:59Z",
        "starts_at": "2025-07-06T16:00:00Z",
        "ends_at": "2025-07-10T18:59:59Z",
        "is_active": False,
        "is_completed": False,
    },
    {
        "name": "Group Stage Week 3",
        "number": 3,
        "selection_opens": "2025-07-06T16:00:00Z",
        "selection_closes": "2025-07-10T17:59:59Z",
        "starts_at": "2025-07-10T19:00:00Z",
        "ends_at": "2025-07-16T18:59:59Z",
        "is_active": False,
        "is_completed": False,
    },
    {
        "name": "Quarter Finals",
        "number": 4,
        "selection_opens": "2025-07-10T19:00:00Z",
        "selection_closes": "2025-07-16T17:59:59Z",
        "starts_at": "2025-07-16T19:00:00Z",
        "ends_at": "2025-07-22T18:59:59Z",
        "is_active": False,
        "is_completed": False,
    },
    {
        "name": "Semi Finals",
        "number": 5,
        "selection_opens": "2025-07-16T19:00:00Z",
        "selection_closes": "2025-07-22T17:59:59Z",
        "starts_at": "2025-07-22T19:00:00Z",
        "ends_at": "2025-07-27T15:59:59Z",
        "is_active": False,
        "is_completed": False,
    },
    {
        "name": "Final",
        "number": 6,
        "selection_opens": "2025-07-22T19:00:00Z",
        "selection_closes": "2025-07-28T14:59:59Z",
        "starts_at": "2025-07-28T16:00:00Z",
        "ends_at": "2025-07-28T23:59:59Z",
        "is_active": False,
        "is_completed": False,
    },
]
