"""
Django settings for weuro2025 project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https:#docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https:#docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS").split(",")

# Railway-specific settings
RAILWAY_STATIC_URL = config("RAILWAY_STATIC_URL", default="")
RAILWAY_ENVIRONMENT = config("RAILWAY_ENVIRONMENT", default="")

# Add Railway domains to allowed hosts
if RAILWAY_ENVIRONMENT:
    ALLOWED_HOSTS.extend(
        [f"*.up.railway.app", f"*.railway.app", "gsheir.com", "www.gsheir.com"]
    )

# Application definition
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "corsheaders",
]

LOCAL_APPS = [
    "game",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "weuro2025.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "weuro2025.wsgi.application"

# Database
# https:#docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https:#docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https:#docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https:#docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Use WhiteNoise for static file serving
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https:#docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom settings
LOGIN_URL = "/weuro2025_game/login/"
LOGIN_REDIRECT_URL = "/weuro2025_game/"
LOGOUT_REDIRECT_URL = "/"

# FBR API settings
FBR_API_BASE_URL = "https:#fbrapi.com/"

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http:#localhost:3000",
    "http:#127.0.0.1:3000",
    "https:#gsheir.com",
]

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "game.services.fbr_api": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "game.management.commands": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Hardcoded football data
WEURO_2025_ROUNDS = [
    {
        "name": "Group Stage Week 1",
        "number": 1,
        "selection_opens": "2025-06-01T00:00:00Z",
        "selection_closes": "2025-07-02T15:00:00Z",
        "starts_at": "2025-07-02T16:00:00Z",
        "ends_at": "2025-07-06T15:59:59Z",
        "is_active": True,
        "is_completed": False,
    },
    {
        "name": "Group Stage Week 2",
        "number": 2,
        "selection_opens": "2025-07-02T16:00:00Z",
        "selection_closes": "2025-07-06T14:59:59Z",
        "starts_at": "2025-07-06T16:00:00Z",
        "ends_at": "2025-07-10T18:59:59Z",
        "is_active": False,
        "is_completed": False,
    },
    {
        "name": "Group Stage Week 3",
        "number": 3,
        "selection_opens": "2025-07-06T16:00:00Z",
        "selection_closes": "2025-07-10T17:59:59Z",
        "starts_at": "2025-07-10T19:00:00Z",
        "ends_at": "2025-07-16T18:59:59Z",
        "is_active": False,
        "is_completed": False,
    },
    {
        "name": "Quarter Finals",
        "number": 4,
        "selection_opens": "2025-07-10T19:00:00Z",
        "selection_closes": "2025-07-16T17:59:59Z",
        "starts_at": "2025-07-16T19:00:00Z",
        "ends_at": "2025-07-22T18:59:59Z",
        "is_active": False,
        "is_completed": False,
    },
    {
        "name": "Semi Finals",
        "number": 5,
        "selection_opens": "2025-07-16T19:00:00Z",
        "selection_closes": "2025-07-22T17:59:59Z",
        "starts_at": "2025-07-22T19:00:00Z",
        "ends_at": "2025-07-27T15:59:59Z",
        "is_active": False,
        "is_completed": False,
    },
    {
        "name": "Final",
        "number": 6,
        "selection_opens": "2025-07-22T19:00:00Z",
        "selection_closes": "2025-07-28T14:59:59Z",
        "starts_at": "2025-07-28T16:00:00Z",
        "ends_at": "2025-07-28T23:59:59Z",
        "is_active": False,
        "is_completed": False,
    },
]

WEURO_2025_PLAYERS = [
  # Finland
  {"name": "Tinja-Riika Korpela", "team": "Finland"},
  {"name": "Anna Tamminen", "team": "Finland"},
  {"name": "Anna Koivunen", "team": "Finland"},
  {"name": "Natalia Kuikka", "team": "Finland"},
  {"name": "Joanna Tynnila", "team": "Finland"},
  {"name": "Eva Nystrom", "team": "Finland"},
  {"name": "Emma Koivisto", "team": "Finland"},
  {"name": "Nora Heroum", "team": "Finland"},
  {"name": "Nea Lehtola", "team": "Finland"},
  {"name": "Emmi Siren", "team": "Finland"},
  {"name": "Maaria Roth", "team": "Finland"},
  {"name": "Vilma Koivisto", "team": "Finland"},
  {"name": "Eveliina Summanen", "team": "Finland"},
  {"name": "Oona Siren", "team": "Finland"},
  {"name": "Olga Ahtinen", "team": "Finland"},
  {"name": "Ria Oling", "team": "Finland"},
  {"name": "Katariina Kosola", "team": "Finland"},
  {"name": "Adelina Engman", "team": "Finland"},
  {"name": "Heidi Kollanen", "team": "Finland"},
  {"name": "Sanni Franssi", "team": "Finland"},
  {"name": "Linda Sallstrom", "team": "Finland"},
  {"name": "Jutta Rantala", "team": "Finland"},
  {"name": "Oona Sevenius", "team": "Finland"},

  # Iceland
  {"name": "Cecilia Ran Runarsdottir", "team": "Iceland"},
  {"name": "Fanney Inga Birkisdottir", "team": "Iceland"},
  {"name": "Telma Ivarsdottir", "team": "Iceland"},
  {"name": "Gudny Arnadottir", "team": "Iceland"},
  {"name": "Ingibjorg Sigurdardottir", "team": "Iceland"},
  {"name": "Glodis Perla Viggosdottir", "team": "Iceland"},
  {"name": "Gudrun Arnardottir", "team": "Iceland"},
  {"name": "Natasha Moraa Anasi", "team": "Iceland"},
  {"name": "Sædis Run Heidarsdottir", "team": "Iceland"},
  {"name": "Aslaug Munda Gunnlaugsdottir", "team": "Iceland"},
  {"name": "Alexandra Johannsdottir", "team": "Iceland"},
  {"name": "Berglind Ros Agustsdottir", "team": "Iceland"},
  {"name": "Katla Tryggvadottir", "team": "Iceland"},
  {"name": "Karolina Lea Vilhjalmsdottir", "team": "Iceland"},
  {"name": "Dagny Brynjarsdottir", "team": "Iceland"},
  {"name": "Hildur Antonsdottir", "team": "Iceland"},
  {"name": "Sandra Maria Jessen", "team": "Iceland"},
  {"name": "Hafrun Rakel Halldorsdottir", "team": "Iceland"},
  {"name": "Dilja Yr Zomers", "team": "Iceland"},
  {"name": "Sveindis Jane Jonsdottir", "team": "Iceland"},
  {"name": "Hlin Eiriksdottir", "team": "Iceland"},
  {"name": "Amanda Jacobsen Andradottir", "team": "Iceland"},
  {"name": "Agla Maria Albertsdottir", "team": "Iceland"},

  # Norway
  {"name": "Cecilie Fiskerstrand", "team": "Norway"},
  {"name": "Aurora Mikalsen", "team": "Norway"},
  {"name": "Selma Panengstuen", "team": "Norway"},
  {"name": "Guro Bergsvand", "team": "Norway"},
  {"name": "Thea Bjelde", "team": "Norway"},
  {"name": "Marit Bratberg Lund", "team": "Norway"},
  {"name": "Tuva Hansen", "team": "Norway"},
  {"name": "Mathilde Harviken", "team": "Norway"},
  {"name": "Maren Mjelde", "team": "Norway"},
  {"name": "Emilie Woldvik", "team": "Norway"},
  {"name": "Vilde Boe Risa", "team": "Norway"},
  {"name": "Ingrid Engen", "team": "Norway"},
  {"name": "Signe Gaupset", "team": "Norway"},
  {"name": "Justine Kielland", "team": "Norway"},
  {"name": "Frida Maanum", "team": "Norway"},
  {"name": "Lisa Naaslund", "team": "Norway"},
  {"name": "Guro Reiten", "team": "Norway"},
  {"name": "Celin Bizet", "team": "Norway"},
  {"name": "Caroline Graham Hansen", "team": "Norway"},
  {"name": "Ada Hegerberg", "team": "Norway"},
  {"name": "Synne Jensen", "team": "Norway"},
  {"name": "Karina Saevik", "team": "Norway"},
  {"name": "Elisabeth Terland", "team": "Norway"},

  # Switzerland
  {"name": "Nadine Bohi", "team": "Switzerland"},
  {"name": "Elvira Herzog", "team": "Switzerland"},
  {"name": "Livia Peng", "team": "Switzerland"},
  {"name": "Laia Balleste", "team": "Switzerland"},
  {"name": "Viola Calligaris", "team": "Switzerland"},
  {"name": "Noelle Maritz", "team": "Switzerland"},
  {"name": "Nadine Riesen", "team": "Switzerland"},
  {"name": "Julia Stierli", "team": "Switzerland"},
  {"name": "Noemi Ivelj", "team": "Switzerland"},
  {"name": "Sandrine Mauron", "team": "Switzerland"},
  {"name": "Coumba Sow", "team": "Switzerland"},
  {"name": "Smilla Vallotto", "team": "Switzerland"},
  {"name": "Lia Walti", "team": "Switzerland"},
  {"name": "Riola Xhemaili", "team": "Switzerland"},
  {"name": "Iman Beney", "team": "Switzerland"},
  {"name": "Ana-Maria Crnogorcevic", "team": "Switzerland"},
  {"name": "Svenja Folmli", "team": "Switzerland"},
  {"name": "Alisha Lehmann", "team": "Switzerland"},
  {"name": "Alayah Pilgrim", "team": "Switzerland"},
  {"name": "Geraldine Reuteler", "team": "Switzerland"},
  {"name": "Sydney Schertenleib", "team": "Switzerland"},
  {"name": "Meriame Terchoun", "team": "Switzerland"},
  {"name": "Leila Wandeler", "team": "Switzerland"},

  # Belgium
  {"name": "Femke Bastiaen", "team": "Belgium"},
  {"name": "Nicky Evrard", "team": "Belgium"},
  {"name": "Lisa Lichtfus", "team": "Belgium"},
  {"name": "Janice Cayman", "team": "Belgium"},
  {"name": "Laura Deloose", "team": "Belgium"},
  {"name": "Isabelle Iliano", "team": "Belgium"},
  {"name": "Jill Janssens", "team": "Belgium"},
  {"name": "Sari Kees", "team": "Belgium"},
  {"name": "Zenia Mertens", "team": "Belgium"},
  {"name": "Davina Philtjens", "team": "Belgium"},
  {"name": "Amber Tysiak", "team": "Belgium"},
  {"name": "Tine De Caigny", "team": "Belgium"},
  {"name": "Marie Detruyer", "team": "Belgium"},
  {"name": "Elena Dhont", "team": "Belgium"},
  {"name": "Kassandra Missipo", "team": "Belgium"},
  {"name": "Jarne Teulings", "team": "Belgium"},
  {"name": "Justine Vanhaevermaet", "team": "Belgium"},
  {"name": "Sarah Wijnants", "team": "Belgium"},
  {"name": "Jassina Blom", "team": "Belgium"},
  {"name": "Hannah Eurlings", "team": "Belgium"},
  {"name": "Mariam Toloba", "team": "Belgium"},
  {"name": "Ella Van Kerkhoven", "team": "Belgium"},
  {"name": "Tessa Wullaert", "team": "Belgium"},

  # Italy
  {"name": "Rachele Baldi", "team": "Italy"},
  {"name": "Francesca Durante", "team": "Italy"},
  {"name": "Laura Giuliani", "team": "Italy"},
  {"name": "Lisa Boattin", "team": "Italy"},
  {"name": "Lucia Di Guglielmo", "team": "Italy"},
  {"name": "Martina Lenzini", "team": "Italy"},
  {"name": "Elena Linari", "team": "Italy"},
  {"name": "Elisabetta Oliviero", "team": "Italy"},
  {"name": "Julie Piga", "team": "Italy"},
  {"name": "Cecilia Salvai", "team": "Italy"},
  {"name": "Arianna Caruso", "team": "Italy"},
  {"name": "Manuela Giugliano", "team": "Italy"},
  {"name": "Eleonora Goldoni", "team": "Italy"},
  {"name": "Giada Greggi", "team": "Italy"},
  {"name": "Eva Schatzer", "team": "Italy"},
  {"name": "Annamaria Serturini", "team": "Italy"},
  {"name": "Emma Severini", "team": "Italy"},
  {"name": "Chiara Beccari", "team": "Italy"},
  {"name": "Barbara Bonansea", "team": "Italy"},
  {"name": "Michela Cambiaghi", "team": "Italy"},
  {"name": "Sofia Cantore", "team": "Italy"},
  {"name": "Cristiana Girelli", "team": "Italy"},
  {"name": "Martina Piemonte", "team": "Italy"},

  # Spain
  {"name": "Adriana Naclares", "team": "Spain"},
  {"name": "Cata Coll", "team": "Spain"},
  {"name": "Esther Sullastres", "team": "Spain"},
  {"name": "Laia Aleixandri", "team": "Spain"},
  {"name": "Ona Battle", "team": "Spain"},
  {"name": "Olga Carmona", "team": "Spain"},
  {"name": "Jana Fernandez", "team": "Spain"},
  {"name": "Maria Mendez", "team": "Spain"},
  {"name": "Leila Ouahabi", "team": "Spain"},
  {"name": "Irene Paredes", "team": "Spain"},
  {"name": "Aitana Bonmati", "team": "Spain"},
  {"name": "Patricia Guijarro", "team": "Spain"},
  {"name": "Vicky Lopez", "team": "Spain"},
  {"name": "Alexia Putellas", "team": "Spain"},
  {"name": "Maite Zubieta", "team": "Spain"},
  {"name": "Mariona Caldentey", "team": "Spain"},
  {"name": "Athenea del Castillo", "team": "Spain"},
  {"name": "Lucia Garcia", "team": "Spain"},
  {"name": "Esther Gonzalez", "team": "Spain"},
  {"name": "Cristina Martin-Prieto", "team": "Spain"},
  {"name": "Salma Paralluelo", "team": "Spain"},
  {"name": "Claudia Pina", "team": "Spain"},
  {"name": "Alba Redondo", "team": "Spain"},

  # Portugal
  {"name": "Ines Pereira", "team": "Portugal"},
  {"name": "Patricia Morais", "team": "Portugal"},
  {"name": "Sierra Cota-Yarde", "team": "Portugal"},
  {"name": "Ana Seica", "team": "Portugal"},
  {"name": "Diana Gomes", "team": "Portugal"},
  {"name": "Catarina Amado", "team": "Portugal"},
  {"name": "Carole Costa", "team": "Portugal"},
  {"name": "Carolina Correia", "team": "Portugal"},
  {"name": "Lucia Alves", "team": "Portugal"},
  {"name": "Ana Borges", "team": "Portugal"},
  {"name": "Joana Marchao", "team": "Portugal"},
  {"name": "Andreia Jacinto", "team": "Portugal"},
  {"name": "Tatiana Pinto", "team": "Portugal"},
  {"name": "Andreia Faria", "team": "Portugal"},
  {"name": "Andreia Norton", "team": "Portugal"},
  {"name": "Fatima Pinto", "team": "Portugal"},
  {"name": "Beatriz Fonseca", "team": "Portugal"},
  {"name": "Francisca Nazareth", "team": "Portugal"},
  {"name": "Dolores Silva", "team": "Portugal"},
  {"name": "Jessica Silva", "team": "Portugal"},
  {"name": "Telma Encarnacao", "team": "Portugal"},
  {"name": "Diana Silva", "team": "Portugal"},
  {"name": "Ana Capeta", "team": "Portugal"},

  # Germany
  {"name": "Ann Katrin-Berger", "team": "Germany"},
  {"name": "Stina Johannes", "team": "Germany"},
  {"name": "Ena Mahmutovic", "team": "Germany"},
  {"name": "Giulia Gwinn", "team": "Germany"},
  {"name": "Kathrin Hendrich", "team": "Germany"},
  {"name": "Franziska Kett", "team": "Germany"},
  {"name": "Sophia Kleinherne", "team": "Germany"},
  {"name": "Rebecca Knaak", "team": "Germany"},
  {"name": "Sarai Linder", "team": "Germany"},
  {"name": "Janina Minge", "team": "Germany"},
  {"name": "Carlotta Wamser", "team": "Germany"},
  {"name": "Sara Dabritz", "team": "Germany"},
  {"name": "Linda Dallmann", "team": "Germany"},
  {"name": "Sydney Lohmann", "team": "Germany"},
  {"name": "Sjoeke Nusken", "team": "Germany"},
  {"name": "Elisa Senss", "team": "Germany"},
  {"name": "Jule Brand", "team": "Germany"},
  {"name": "Klara Buhl", "team": "Germany"},
  {"name": "Selina Cerci", "team": "Germany"},
  {"name": "Laura Freigang", "team": "Germany"},
  {"name": "Giovanna Hoffmann", "team": "Germany"},
  {"name": "Lea Schuller", "team": "Germany"},
  {"name": "Cora Zicai", "team": "Germany"},

  # Poland
  {"name": "Natalia Radkiewicz", "team": "Poland"},
  {"name": "Kinga Szemik", "team": "Poland"},
  {"name": "Kinga Seweryn", "team": "Poland"},
  {"name": "Kayla Adamek", "team": "Poland"},
  {"name": "Paulina Dudek", "team": "Poland"},
  {"name": "Sylwia Matysik", "team": "Poland"},
  {"name": "Emilia Szymczak", "team": "Poland"},
  {"name": "Martyna Wiankowska", "team": "Poland"},
  {"name": "Oliwia Wos", "team": "Poland"},
  {"name": "Wiktoria Zieniewicz", "team": "Poland"},
  {"name": "Adriana Achcinska", "team": "Poland"},
  {"name": "Martyna Brodzik", "team": "Poland"},
  {"name": "Dominika Grabowska", "team": "Poland"},
  {"name": "Ewelina Kamczyk", "team": "Poland"},
  {"name": "Milena Kokosz", "team": "Poland"},
  {"name": "Tanja Pawollek", "team": "Poland"},
  {"name": "Klaudia Słowinska", "team": "Poland"},
  {"name": "Klaudia Jedlinska", "team": "Poland"},
  {"name": "Nadia Krezyman", "team": "Poland"},
  {"name": "Natalia Padilla-Bidas", "team": "Poland"},
  {"name": "Ewa Pajor", "team": "Poland"},
  {"name": "Paulina Tomasiak", "team": "Poland"},
  {"name": "Weronika Zawistowska", "team": "Poland"},

  # Denmark
  {"name": "Alberte Vingum", "team": "Denmark"},
  {"name": "Kathrine Larsen", "team": "Denmark"},
  {"name": "Maja Bay Ostergaard", "team": "Denmark"},
  {"name": "Emma Faerge", "team": "Denmark"},
  {"name": "Frederikke Thogersen", "team": "Denmark"},
  {"name": "Isabella Obaze", "team": "Denmark"},
  {"name": "Katrine Veje", "team": "Denmark"},
  {"name": "Sanne Troelsgaard", "team": "Denmark"},
  {"name": "Sara Holmgaard", "team": "Denmark"},
  {"name": "Sara Thrige", "team": "Denmark"},
  {"name": "Stine Ballisager", "team": "Denmark"},
  {"name": "Emma Snerle", "team": "Denmark"},
  {"name": "Janni Thomsen", "team": "Denmark"},
  {"name": "Josefine Hasbo", "team": "Denmark"},
  {"name": "Karen Holmgaard", "team": "Denmark"},
  {"name": "Kathrine Kuhl", "team": "Denmark"},
  {"name": "Rikke Madsen", "team": "Denmark"},
  {"name": "Amalie Vangsgaard", "team": "Denmark"},
  {"name": "Cornelia Kramer", "team": "Denmark"},
  {"name": "Nadia Nadim", "team": "Denmark"},
  {"name": "Pernille Harder", "team": "Denmark"},
  {"name": "Signe Bruun", "team": "Denmark"},
  {"name": "Sofie Bredgaard", "team": "Denmark"},

  # Sweden
  {"name": "Tove Enblom", "team": "Sweden"},
  {"name": "Jennifer Falk", "team": "Sweden"},
  {"name": "Emma Holmgren", "team": "Sweden"},
  {"name": "Jonna Andersson", "team": "Sweden"},
  {"name": "Nathalie Bjorn", "team": "Sweden"},
  {"name": "Magdalena Eriksson", "team": "Sweden"},
  {"name": "Smilla Holmberg", "team": "Sweden"},
  {"name": "Amanda Ilestedt", "team": "Sweden"},
  {"name": "Hanna Lunfkvist", "team": "Sweden"},
  {"name": "Amanda Nilden", "team": "Sweden"},
  {"name": "Linda Sembrant", "team": "Sweden"},
  {"name": "Filippa Angeldahl", "team": "Sweden"},
  {"name": "Hanna Bennison", "team": "Sweden"},
  {"name": "Sofia Jakobsson", "team": "Sweden"},
  {"name": "Madelen Janogy", "team": "Sweden"},
  {"name": "Johanna Rytting Kaneryd", "team": "Sweden"},
  {"name": "Julia Zigiotti Olme", "team": "Sweden"},
  {"name": "Kosovare Asllani", "team": "Sweden"},
  {"name": "Stina Blackstenius", "team": "Sweden"},
  {"name": "Rebecka Blomqvist", "team": "Sweden"},
  {"name": "Lina Hurtig", "team": "Sweden"},
  {"name": "Fridolina Rolfo", "team": "Sweden"},
  {"name": "Ellen Wangerheim", "team": "Sweden"},

  # England
  {"name": "Hannah Hampton", "team": "England"},
  {"name": "Khiara Keating", "team": "England"},
  {"name": "Anna Moorhouse", "team": "England"},
  {"name": "Lucy Bronze", "team": "England"},
  {"name": "Leah Williamson", "team": "England"},
  {"name": "Jess Carter", "team": "England"},
  {"name": "Alex Greenwood", "team": "England"},
  {"name": "Lotte Wubben-Moy", "team": "England"},
  {"name": "Esme Morgan", "team": "England"},
  {"name": "Niamh Charles", "team": "England"},
  {"name": "Maya Le Tissier", "team": "England"},
  {"name": "Ella Toone", "team": "England"},
  {"name": "Georgia Stanway", "team": "England"},
  {"name": "Keira Walsh", "team": "England"},
  {"name": "Grace Clinton", "team": "England"},
  {"name": "Jess Park", "team": "England"},
  {"name": "Lauren Hemp", "team": "England"},
  {"name": "Lauren James", "team": "England"},
  {"name": "Chloe Kelly", "team": "England"},
  {"name": "Beth Mead", "team": "England"},
  {"name": "Michelle Agyemang", "team": "England"},
  {"name": "Alessia Russo", "team": "England"},
  {"name": "Aggie Beever-Jones", "team": "England"},

  # Netherlands
  {"name": "Danielle de Jong", "team": "Netherlands"},
  {"name": "Lize Kop", "team": "Netherlands"},
  {"name": "Daphne van Domselaar", "team": "Netherlands"},
  {"name": "Veerle Buurman", "team": "Netherlands"},
  {"name": "Kerstin Casparij", "team": "Netherlands"},
  {"name": "Caitlin Dijkstra", "team": "Netherlands"},
  {"name": "Dominique Janssen", "team": "Netherlands"},
  {"name": "Ilse van der Zanden", "team": "Netherlands"},
  {"name": "Lynn Wilms", "team": "Netherlands"},
  {"name": "Damaris Egurrola", "team": "Netherlands"},
  {"name": "Jackie Groenen", "team": "Netherlands"},
  {"name": "Wieke Kaptein", "team": "Netherlands"},
  {"name": "Victoria Pelova", "team": "Netherlands"},
  {"name": "Jill Roord", "team": "Netherlands"},
  {"name": "Sherida Spitse", "team": "Netherlands"},
  {"name": "Danielle van de Donk", "team": "Netherlands"},
  {"name": "Lineth Beerensteyn", "team": "Netherlands"},
  {"name": "Esmee Brugts", "team": "Netherlands"},
  {"name": "Chasity Grant", "team": "Netherlands"},
  {"name": "Renate Jansen", "team": "Netherlands"},
  {"name": "Romee Leuchte", "team": "Netherlands"},
  {"name": "Vivianne Miedema", "team": "Netherlands"},
  {"name": "Katja Snoeijs", "team": "Netherlands"},

  # France
  {"name": "Justine Lerond", "team": "France"},
  {"name": "Pauline Peyraud-Magnin", "team": "France"},
  {"name": "Constance Picaud", "team": "France"},
  {"name": "Selma Bacha", "team": "France"},
  {"name": "Lou Bogaert", "team": "France"},
  {"name": "Elisa De Almeida", "team": "France"},
  {"name": "Maelle Lakrar", "team": "France"},
  {"name": "Griedge Mbock", "team": "France"},
  {"name": "Melween N'Dongala", "team": "France"},
  {"name": "Thiniba Samoura", "team": "France"},
  {"name": "Alice Sombath", "team": "France"},
  {"name": "Sandy Baltimore", "team": "France"},
  {"name": "Grace Geyoro", "team": "France"},
  {"name": "Oriane Jean-Francois", "team": "France"},
  {"name": "Sakina Karchaoui", "team": "France"},
  {"name": "Amel Majri", "team": "France"},
  {"name": "Sandie Toletti", "team": "France"},
  {"name": "Delphine Cascarino", "team": "France"},
  {"name": "Kadiatou Diani", "team": "France"},
  {"name": "Kelly Gago", "team": "France"},
  {"name": "Marie-Antoinette Katoto", "team": "France"},
  {"name": "Melvine Malard", "team": "France"},
  {"name": "Clara Mateo", "team": "France"},

  # Wales
  {"name": "Olivia Clark", "team": "Wales"},
  {"name": "Safia Middleton-Patel", "team": "Wales"},
  {"name": "Poppy Soper", "team": "Wales"},
  {"name": "Charlie Estcourt", "team": "Wales"},
  {"name": "Gemma Evans", "team": "Wales"},
  {"name": "Josie Green", "team": "Wales"},
  {"name": "Hayley Ladd", "team": "Wales"},
  {"name": "Esther Morgan", "team": "Wales"},
  {"name": "Ella Powell", "team": "Wales"},
  {"name": "Rhiannon Roberts", "team": "Wales"},
  {"name": "Lily Woodham", "team": "Wales"},
  {"name": "Jess Fishlock", "team": "Wales"},
  {"name": "Alice Griffiths", "team": "Wales"},
  {"name": "Ceri Holland", "team": "Wales"},
  {"name": "Sophie Ingle", "team": "Wales"},
  {"name": "Angharad James", "team": "Wales"},
  {"name": "Lois Joel", "team": "Wales"},
  {"name": "Rachel Rowe", "team": "Wales"},
  {"name": "Kayleigh Barton", "team": "Wales"},
  {"name": "Hannah Cain", "team": "Wales"},
  {"name": "Elise Hughes", "team": "Wales"},
  {"name": "Carrie Jones", "team": "Wales"},
  {"name": "Ffion Morgan", "team": "Wales"}
]